import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from '../app/components/Header';
import SideNavbar from '../app/components/SideNavbar';

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex">
          <SideNavbar / >
          <div className="flex-1 md:flex h-screen relative overflow-auto ">
          <Header />
          <main className="  w-full h-full ">{children}</main>
        </div>
        </div>
      </body>
    </html>
  );
}
